config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'homes/top'
  # get 'tweets/new'
  # get 'tweets/create'
  # get 'tweets/index'
  # get 'tweets/show'
  # get 'tweets/edit'
  # get 'tweets/update'
  # get 'tweets/destroy'
  # get 'users/index'
  # get 'users/show'
  # get 'users/edit'
  # get 'users/update'
  devise_for :users
  root 'homes#top'
  get 'tweets/hashtag' => 'tweets#hashtag'
  resources :tweets
  resources :users
  resources :tags, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :tweet_tags, dependent: :destroy
	has_many :tweets, through: :tweet_tags, dependent: :destroy
end

app/models/tweet.rb
# frozen_string_literal: true

class Tweet < ApplicationRecord
  	belongs_to :user
	validates :body, presence: true

	after_create do
		tags = self.body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
		tags.uniq.map do |t|
			tag = Tag.find_or_create_by(tag_name: t.downcase.delete('#'))
			TweetTag.find_or_create_by(tweet_id:self.id,tag_id:tag.id)
		end
	end
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
	belongs_to :tweet
	belongs_to :tag
	validates :tweet_id, presence: true
	validates :tag_id, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image
  has_many :tweets, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected
		def configure_permitted_parameters
			devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :adult])
		end
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  def top; end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	before_action :authenticate_user!

	def show
		@tag = Tag.find(params[:id])
		@tweets = @tag.tweets
	end
end

app/controllers/tweets_controller.rb
# frozen_string_literal: true

class TweetsController < ApplicationController

	before_action :authenticate_user!

	def new
		@tweet = Tweet.new
	end

	def create
		@tweet = Tweet.new(tweet_params)
		@tweet.user_id = current_user.id
		if @tweet.save
		   redirect_to tweets_path
		else
		   render :new
		end
	end

	def index
		@tweets = Tweet.all
	end

	def hashtag
		@tag = Tag.find_by(tag_name: params[:tag_name])
		if  @tag.present?
			@tweets = @tag.tweets
		else
			@tweets = Tweet.all
		end
		@tag_lists = Tag.all
	end

	# def show
	# 	@tweet = Tweet.find(params[:id])
	# 	@comment = Comment.new
	# 	@comments = @tweet.comments.page(params[:page]).per(5)
	# end

	# def edit
	# 	@tweet = Tweet.find(params[:id])
	# end

	# def update
	# 	@tweet = Tweet.find(params[:id])
	# 	if @tweet.update(tweet_params)
	# 	   redirect_to tweets_path
	# 	else
	# 	   render :edit
	# 	end
	# end

	# def destroy
	# 	@tweet = Tweet.find(params[:id])
	# 	@tweet.destroy
	# 	redirect_to tweets_path
	# end

	private
	def tweet_params
		params.require(:tweet).permit(:body)
	end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController

	before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @tweets = Tweet.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user)
    else
       render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :image, :introduction, :history, :favorite_alcohol)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/homes_helper.rb
# frozen_string_literal: true

module HomesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tweets_helper.rb
# frozen_string_literal: true

module TweetsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shirafu2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
          <% if user_signed_in? %>
            <%= link_to"Shirafu", root_path %>
            <%= link_to"Tweet", tweets_path %>
            <%= link_to"Search", tweets_hashtag_path %>
            <%= link_to"New", new_tweet_path %>
            <%= link_to"User", users_path %>
            <%= link_to"logout", destroy_user_session_path, method: :delete %>
      <% else %>
            <%= link_to"Shirafu", root_path %>
            <%= link_to"Signup",new_user_registration_path %>
            <%= link_to"login",new_user_session_path %>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/tags/show.html.erb
<table>
	<% @tweets.each do |tweet| %>
	<tr>
		<td><%= attachment_image_tag tweet.user, :image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", size:'70x70' %></td>
		<td><%= link_to tweet.user.name, user_path(tweet.user) %></td>
		<td><%= tweet.body %></td>
	</tr>
	<% end %>
</table>

app/views/tweets/edit.html.erb
<h1>Tweets#edit</h1>
<p>Find me in app/views/tweets/edit.html.erb</p>

app/views/tweets/hashtag.html.erb
<%= form_tag(tweets_hashtag_path, method: :get) do %>
	<%= label_tag(:tag_name, "#タグで探す") %>
	<%= text_field_tag(:tag_name) %>
	<%= submit_tag"Search" %>
<% end %>

<div class="container">
	<div class="row">
		<div class="col-xs-6">
			<p style="color: blue">タグ一覧</p>
			<table>
			<% @tag_lists. shuffle. first(5). each do |tag| %>
				<tr>
				<td><%= link_to tag.tag_name, tag_path(tag) %></td>
				</tr>
			<% end %><br>
			</table>
		</div>

		<div class="col-xs-6">
			<p style="color: blue">タグ検索後ツイート一覧</p>
			<table>
			<% @tweets.each do |tweet| %>
				<tr>
				<td><%= attachment_image_tag tweet.user, :image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", size:'70x70' %></td>
				<td><%= link_to tweet.user.name, user_path(tweet.user) %></td>
				<td><%= tweet.body %></td>
				</tr>
			<% end %>
			</table>
		</div>
	</div>
</div>

app/views/tweets/index.html.erb
<table>
	<% @tweets.each do |tweet| %>
	<tr>
		<td><%= attachment_image_tag tweet.user, :image, :fill, 80, 80, format: 'jpeg', fallback: "no_image.jpg", size:'80x80' %></td>
		<td><%= link_to tweet.user.name, user_path(tweet.user) %></td>
		<td><%= tweet.body %></td>
	</tr>
	<% end %>
</table>

app/views/tweets/new.html.erb
<%= form_for(@tweet) do |f| %>
	<%= f.text_area :body %>
	<%= f.submit 'Shirafuru' %>
		<% if @tweet.errors.any? %>
			<!-- tweet body validation有りの為　空欄→エラー -->
			<% @tweet.errors.full_messages.each do |message| %>
			<%= message %>
			<% end %>
		<% end %>
<% end %>

app/views/tweets/show.html.erb
<h1>Tweets#show</h1>
<p>Find me in app/views/tweets/show.html.erb</p>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
<%= f.attachment_field :image %><br>
<%= f.label :名前　　　 %>
<%= f.text_field :name %><br>
<%= f.label :自己紹介　　　 %>
<%= f.text_field :introduction %><br>
<%= f.label :禁酒歴　　　 %>
<%= f.text_field :history %><br>
<%= f.label :好きなお酒　　　 %>
<%= f.text_field :favorite_alcohol %><br>
<%= f.submit 'Update' %>
<% end %>

app/views/users/index.html.erb
<table>
	<% @users.each do |user| %>
	<tr>
		<td><%= attachment_image_tag user, :image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", size:'90x90' %></td>
		<td><%= link_to user.name, user_path(user) %></td>
		<td><%= link_to'SHOW', user_path(user) %></td>
	</tr>
	<% end %>
</table>

app/views/users/show.html.erb
<table>
	<tr>
<td><%= attachment_image_tag @user, :image, :fill, 200, 200, format: 'jpg', fallback: "no_image.jpg", size:'200x200'  %></td>
<td><u>名前</u></td>
<td><%= @user.name %></td>
<td><u>自己紹介</u></td>
<td><%= @user.introduction %></td>
<td><u>禁酒歴</u></td>
<td><%= @user.history %></td>
<td><u>好きなお酒</u></td>
<td><%= @user.favorite_alcohol %></td>
<% if @user == current_user %>
<td><%= link_to'Edit', edit_user_path(@user) %></td>
</tr>
<% end %>

</table>